Ecommerce2/Models/Users.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Address = new HashSet<Address>();
            this.Order = new HashSet<Order>();
        }
    
        public int UserID { get; set; }
        public int RoleID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Address> Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        public virtual Roles Roles { get; set; }
    }
}

Ecommerce2/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ecommerce2.Models;
using System.Data.Entity.Infrastructure;
using System.Net;
using Ecommerce2.Controllers;

namespace Ecommerce2.Models
{
    public class OrderController : Controller
    {
        
        private ecommerceEntities ent = new ecommerceEntities();
        [_SessionControl]
        public ActionResult Orders()
        {
            var orders = getOrders();

            return View(orders);
        }
        [_SessionControl]
        public ActionResult OrderDetail(int? id,OrderDetailViewModel model)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = ent.Order.Where(o => o.OrderID == id).FirstOrDefault();
            var orderDetails = ent.OrderDetail.Where(ol => ol.OrderID == id).ToList();

            model.order = order;
            model.orderDetails = orderDetails;
            
            if (order == null)
            {
                return HttpNotFound();
            }

            return View(model);
        }
        [_SessionControl]
        // GET: Order
        public ActionResult CreateOrder()
        {

            List<Cart> carts = listCartItems();
            Users user = getUser();
            decimal total = getTotal();
            var a = listAddress();
            OrderViewModel ord = new OrderViewModel();
            ord.addresses = a;
            ord.cartItems = carts;
            ord.user = user;
            ord.Total = total;
            return View("CreateOrder", ord);

        }


        [HttpPost]
        public ActionResult CreateOrder(Order order,string Address)
        {
            int adrID = int.Parse(Address);
            OrderViewModel model = new OrderViewModel();
            List<Cart> cartItems = listCartItems();
            Users user = getUser();
            Address adr = ent.Address.FirstOrDefault(a=>a.AddressID == adrID);
            order.UserID = user.UserID;
            order.Total = getTotal();
            order.AddressID = adrID;
            ent.Order.Add(order);
 
            foreach (var items in cartItems)
            {
                var orderDetail = new OrderDetail
                {
                    OrderID = order.OrderID,
                    ProductID = items.ProductID,
                    Quantity = items.Count,
                    UnitPrice = items.Product.ProductPrice
                };
                model.orderDetails = orderDetail;
                ent.OrderDetail.Add(orderDetail);
            }

            ent.SaveChanges();
            ent.removeCart(user.Username);
            ent.SaveChanges();
            model.cartItems = cartItems;
            model.order = order;
            model.Total = order.Total;

            return View("Complete", model);
        }

        private decimal getTotal()
        {
            var usr = User.Identity.Name.ToString();
            decimal? total = (from cartItems in ent.Cart
                              where cartItems.CartID == usr
                              select (int?)cartItems.Count * cartItems.Product.ProductPrice).Sum();
            return total ?? decimal.Zero;
        }

        private List<Cart> listCartItems()
        {
            var usr = User.Identity.Name.ToString();
            List<Cart> carts = (from data in ent.Cart
                                join data2 in ent.Users on data.CartID equals data2.Username
                                join data3 in ent.Product on data.ProductID equals data3.ProductID
                                where data2.Username.Equals(usr)
                                select data).ToList();

            return carts;
        }

        private List<Address> listAddress()
        {
            var usr = User.Identity.Name.ToString();
            Users usrID = ent.Users.FirstOrDefault(u => u.Username == usr);
            var a = ent.Address.Where(u => u.UserID == usrID.UserID).ToList();
            return a;

        }

        private Users getUser()
        {
            var usr = User.Identity.Name.ToString();

            return ent.Users.FirstOrDefault(u => u.Username == usr);


        }
        private List<Order> getOrders()
        {
            var usr = User.Identity.Name.ToString();
            Users user = ent.Users.FirstOrDefault(u => u.Username == usr);
            var order = ent.Order.Where(o => o.UserID == user.UserID).ToList();
            return order;
        }


    }
}

Ecommerce2/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ecommerce2.Models;
using System.Net;
using System.Data.Entity.Infrastructure;
using System.Data.Entity;
using System.Data.Entity.Core.Objects;
using System.Web.Security;

namespace Ecommerce2.Controllers
{
    public class UserController : Controller
    {


        private ecommerceEntities ent = new ecommerceEntities();

        [_SessionControl]
        //GET: User
        public ActionResult Users()
        {
            return View(ent.Users.ToList());
        }


        [_SessionControl]
        //GET: User/Details/5
        public ActionResult Details()
        {
            if (User.Identity.IsAuthenticated) {

                Users user = ent.Users.FirstOrDefault(u => u.Username.Equals(User.Identity.Name.ToString()));

                if (user.UserID == 0)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                var usr = ent.Users.Find(user.UserID);

                if(usr == null)
                {
                    return HttpNotFound();
                }

                return View(usr);
            }

           
            return RedirectToAction("Home/index");

        }
       
        // GET: User/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: User/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UserID,Username,Password,Firstname,Lastname,Phone,Email,CreatedAt,ModifiedAt")]Users user,LoginModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    
                    ent.Users.Add(user);
                    ent.SaveChanges();

                    var users = ent.Users.Where(data => data.Username == model.Username && data.Password == data.Password);

                    if (users.Count()>0)
                    {
                        FormsAuthentication.SetAuthCookie(model.Username, true);
                        return RedirectToAction("Index", "Home");
                    }
                    
                }
            }
            catch (DbUpdateException ex)
            {
                throw ex;
            }

            return View(model);
        }

        [_SessionControl]
        // GET: User/Edit/5
        public ActionResult Edit(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Users user = ent.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }

            return View(user);
        }

        // POST: User/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UserID,Username,Password,Firstname,Lastname,Phone,Email,CreatedAt,ModifiedAt")]Users user)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    
                    ent.Entry(user).State = EntityState.Modified;
                    user.ModifiedAt = DateTime.Now;
                    ent.SaveChanges();
                    return RedirectToAction("Products","Product","");
                }
                return View(user);

            }
            catch
            {
                return View();
            }
        }
        [_SessionControl]
        // GET: User/Delete/5
        public ActionResult Delete(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Users user = ent.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }

            return View(user);
        }

        // POST: User/Delete/5
        [HttpPost, ActionName("DELETE")]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            try
            {
                Users user = ent.Users.Find(id);
                ent.Users.Remove(user);
                ent.SaveChanges();
                return RedirectToAction("Users");
            }
            catch
            {
                return View();
            }
        }
    }
}

Ecommerce2/Views/User/Create.cshtml
@model Ecommerce2.Models.Users

@{
    ViewBag.Title = "Create";
}
@section other
{
    <link href="~/Content/EditCreateForm.css" rel="stylesheet" />
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <h2 align="center">Edit Profile</h2>
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3 field-label-responsive">
            <label for="name">Firstname</label>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                    <div class="input-group-addon" style="width: 2.6rem"><i class="fa fa-user" style="margin-left:15px;margin-top:13px;"></i></div>
                    @Html.EditorFor(model => model.Firstname, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-control-feedback">
                <span class="text-danger align-middle">
                    @Html.ValidationMessageFor(model => model.Firstname, "", new { @class = "text-danger" })
                </span>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3 field-label-responsive">
            <label for="name">Lastname</label>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                    <div class="input-group-addon" style="width: 2.6rem"><i class="fa fa-user" style="margin-left:15px;margin-top:13px;"></i></div>
                    @Html.EditorFor(model => model.Lastname, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-control-feedback">
                <span class="text-danger align-middle">
                    @Html.ValidationMessageFor(model => model.Lastname, "", new { @class = "text-danger" })
                </span>
            </div>
        </div>
    </div>
        <div class="row">
            <div class="col-md-3 field-label-responsive">
                <label for="email">E-Mail Address</label>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                        <div class="input-group-addon" style="width: 2.6rem"><i class="fa fa-at" style="margin-left:15px;margin-top:13px;"></i></div>
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-control-feedback">
                    <span class="text-danger align-middle">
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 field-label-responsive">
                <label for="password">Phone</label>
            </div>
            <div class="col-md-6">
                <div class="form-group has-danger">
                    <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                        <div class="input-group-addon" style="width: 2.6rem"><i class="fa fa-phone" style="margin-left:15px;margin-top:13px;"></i></div>
                        @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-control-feedback">
                    <span class="text-danger align-middle">
                        @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                    </span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 field-label-responsive">
                <label for="password">Username</label>
            </div>
            <div class="col-md-6">
                <div class="form-group has-danger">
                    <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                        <div class="input-group-addon" style="width: 2.6rem"><i class="fa fa-user-secret" style="margin-left:15px;margin-top:13px;"></i></div>
                        @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-control-feedback">
                    <span class="text-danger align-middle">
                        @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
                    </span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 field-label-responsive">
                <label for="password">Password</label>
            </div>
            <div class="col-md-6">
                <div class="form-group has-danger">
                    <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                        <div class="input-group-addon" style="width: 2.6rem"><i class="fa fa-key" style="margin-left:15px;margin-top:13px;"></i></div>
                        @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-control-feedback">
                    <span class="text-danger align-middle">
                        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                    </span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                <input type="submit" value="Create" class="btn btn-primary" />
                @Html.ActionLink("Cancel", "Products", "Product", null, new { @class = "btn btn-light" })
            </div>
        </div>
}

Ecommerce2/Views/User/Delete.cshtml
@model Ecommerce2.Models.Users

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Users</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Username)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Firstname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Firstname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lastname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lastname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedAt)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> 
            @Html.ActionLink("Back to Profile", "Details","",new { @class = "btn btn-warning"})
        </div>
    }
</div>

Ecommerce2/Views/User/Details.cshtml
@model Ecommerce2.Models.Users

@{
    ViewBag.Title = "Details";
}
@section other
{
<link href="~/Content/User.css" rel="stylesheet" />
}

<br>
<br>
<div class="card bg-light card-body mb-3 span8 offset2">
    <div class="row-fluid user-infos cyruxx">
        <div class="span10 offset1">
            <div class="card text-white bg-primary">
                <div class="card-header">
                    <h3 class="card-title">User information</h3>
                </div>
                <div class="card-body">
                    <div class="row-fluid">
                        <div class="span3">
                            <img class="rounded-circle" src="https://lh5.googleusercontent.com/-b0-k99FZlyE/AAAAAAAAAAI/AAAAAAAAAAA/eu7opA4byxI/photo.jpg?sz=100"
                                 alt="User Pic">
                        </div>
                        <div class="span6">
                            <strong>@Html.DisplayFor(model => model.Firstname) @Html.DisplayFor(model => model.Lastname)</strong>
                            <br>
                            <table class="table table-sm table-responsive table-user-information">
                                <tbody>
                                    <tr>
                                        <td>Username :</td>
                                        <td>@Html.DisplayFor(model => model.Username)</td>
                                    </tr>
                                    <tr>
                                        <td>Password :</td>
                                        <td>@Html.DisplayFor(model => model.Password)</td>
                                    </tr>
                                    <tr>
                                        <td>Phone :</td>
                                        <td>@Html.DisplayFor(model => model.Phone)</td>
                                    </tr>
                                    <tr>
                                        <td>Email</td>
                                        <td>@Html.DisplayFor(model => model.Email)</td>
                                    </tr>
                                    <tr>
                                        <td>Registeration Date</td>
                                        <td>@Html.DisplayFor(model => model.CreatedAt)</td>
                                    </tr>
                                </tbody>
                            </table>
                            @Html.ActionLink("My Addresses", "Address", "Address", new { id = Model.UserID }, new { @class = "btn btn-light" })
                            @Html.ActionLink("My Orders", "Orders", "Order", new { id = Model.UserID }, new { @class = "btn btn-light" })
                        </div>
                    </div>
                </div>
                <div class="card-footer" style="height:50px;">
                    <span class="float-right">

                        <a href="@Url.Action("Edit","User",new { id = Model.UserID })" data-original-title="Edit this user" data-toggle="tooltip" type="button" class="btn btn-sm btn-light">
                            <i class="fa fa-edit"></i>
                        </a>

                        <a href="@Url.Action("Delete","User",new { id = Model.UserID })" data-original-title="Remove this user" data-toggle="tooltip" type="button" class="btn btn-sm btn-light">
                            <i class="fa fa-remove"></i>
                        </a>

                    </span>
                </div>
            </div>
        </div>
    </div>
</div>

Ecommerce2/Views/User/Edit.cshtml
@model Ecommerce2.Models.Users

@{
    ViewBag.Title = "Edit";
}
@section other
{
    <link href="~/Content/EditCreateForm.css" rel="stylesheet" />
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.UserID)
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <h2 align="center">Edit Profile</h2>
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3 field-label-responsive">
            <label for="name">Firstname</label>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                    <div class="input-group-addon" style="width: 2.6rem"><i class="fa fa-user" style="margin-left:15px;margin-top:13px;"></i></div>
                    @Html.EditorFor(model => model.Firstname, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-control-feedback">
                <span class="text-danger align-middle">
                    @Html.ValidationMessageFor(model => model.Firstname, "", new { @class = "text-danger" })
                </span>
            </div>
        </div>
    </div>
        <div class="row">
            <div class="col-md-3 field-label-responsive">
                <label for="name">Lastname</label>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                        <div class="input-group-addon" style="width: 2.6rem"><i class="fa fa-user" style="margin-left:15px;margin-top:13px;"></i></div>
                        @Html.EditorFor(model => model.Lastname, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-control-feedback">
                    <span class="text-danger align-middle">
                        @Html.ValidationMessageFor(model => model.Lastname, "", new { @class = "text-danger" })
                    </span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 field-label-responsive">
                <label for="email">E-Mail Address</label>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                        <div class="input-group-addon" style="width: 2.6rem"><i class="fa fa-at" style="margin-left:15px;margin-top:13px;"></i></div>
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-control-feedback">
                    <span class="text-danger align-middle">
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 field-label-responsive">
                <label for="password">Phone</label>
            </div>
            <div class="col-md-6">
                <div class="form-group has-danger">
                    <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                        <div class="input-group-addon" style="width: 2.6rem"><i class="fa fa-phone" style="margin-left:15px;margin-top:13px;"></i></div>
                        @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-control-feedback">
                    <span class="text-danger align-middle">
                        @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                    </span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 field-label-responsive">
                <label for="password">Username</label>
            </div>
            <div class="col-md-6">
                <div class="form-group has-danger">
                    <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                        <div class="input-group-addon" style="width: 2.6rem"><i class="fa fa-user-secret" style="margin-left:15px;margin-top:13px;"></i></div>
                        @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-control-feedback">
                    <span class="text-danger align-middle">
                        @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
                    </span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 field-label-responsive">
                <label for="password">Password</label>
            </div>
            <div class="col-md-6">
                <div class="form-group has-danger">
                    <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                        <div class="input-group-addon" style="width: 2.6rem"><i class="fa fa-key" style="margin-left:15px;margin-top:13px;"></i></div>
                        @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-control-feedback">
                    <span class="text-danger align-middle">
                        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                    </span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                <input type="submit" value="Edit" class="btn btn-primary" />
                @Html.ActionLink("Cancel", "Details", "User", null, new { @class = "btn btn-light" })
            </div>
        </div>

}